### ISSUE TITLE
Organize the scripts

### ISSUE THREAD

**Issue by nickworks** [nickworks/TreeOfLife#34]
Move all enemy & NPC scripts into /Scripts/NPCs
Move HealthController.cs into /Scripts/Player

**Comment by AJSmithJohnson** [comment]
All NPC and Enemy Scripts are in Scripts/NPC's, HealthController is in Scripts/Player, all the environmental Scripts are moved into Environment, The path scripts are in a folder labeled Pathing.

This is in the purging colliders branch.

**Comment by AJSmithJohnson** [comment]
I lied I created a new branch off of the purgeColliders Branch.
