### ISSUE TITLE
Organize current prefabs

### ISSUE THREAD

**Issue by nickworks** [nickworks/TreeOfLife#37]
1. Add /Prefabs/Enemies folder
1. Add /Prefabs/Environment folder
1. Move Birb into /Prefabs/Enemies
1. Move FallingPlatform, Platform, Raft, RopePiece, and RopeSpawner into /Prefabs/Environment
1. Move Bug from /Enemies/ into /Prefabs/Enemies/.
1. Destroy /Enemies/ folder.

**Comment by AJSmithJohnson** [comment]
Alright I have prefabs/enemies and prefabs/environment set up. Birb and Bug are in prefabs/enemies and both platforms, the RopePiece, and RopeSpawner are in Prefabs/Environment.

This is in the purging collidersBranch

**Comment by AJSmithJohnson** [comment]
I lied I created a new branch off of the purgeColliders Branch.

**Comment by nickworks** [comment]
Issue closed. Thanks!
