### ISSUE TITLE
Redundant Asset folders: /Graphics/ and /Materials/

### ISSUE THREAD

**Issue by nickworks** [nickworks/TreeOfLife#38]
Move assets from /Graphics/ into /Materials/.

Destroy /Graphics/.

**Comment by AJSmithJohnson** [comment]
I've moved the materials and destroyed graphics. It's in the PurgeCollidersBranch

**Comment by AJSmithJohnson** [comment]
I lied I created a new branch off of the purgeColliders Branch.

**Comment by nickworks** [comment]
Thanks! Issue closed.
