### ISSUE TITLE
Fix/rebuild core prefabs

### ISSUE THREAD

**Issue by nickworks** [nickworks/TreeOfLife#39]
1. Rename /Prefabs/CameraTarget to /Prefabs/CameraRig
1. Remove Rigidbody2D, BoxCollider2D, and PawnAABB from /Prefabs/Player
1. Add PawnAABB3D to /Prefabs/Player

**Comment by AJSmithJohnson** [comment]
I've Removed Rigidbody2D, BoxCollider2D, and PawnAABB from prefab player.
I added PawnAABB3D to prefabs/Player and the players in all the seperate scenes

**Comment by AJSmithJohnson** [comment]
The above is in the purgeCollidersbranch

**Comment by AJSmithJohnson** [comment]
I lied I created a new branch off of the purgeColliders Branch.

**Comment by nickworks** [comment]
Good work! Closing the issue.
