### ISSUE TITLE
Turning delay

### ISSUE THREAD

**Issue by AnIdeaGuy** [nickworks/TreeOfLife#4]
Maybe change the horizontal velocity faster when it's moving left and then moves right, or vice versa.

**Comment by nickworks** [comment]
Added PlayerController.**turnAroundMultiplier** which is used (in PlayerStateRegular) to scale horizontal acceleration when the input is pointing in the opposite direction of the velocity.

Fixed by https://github.com/nickworks/TreeOfLife/commit/de6fda3bc9ee506b1a84ea280e2c0c72b216a979
