### ISSUE TITLE
Change it so the player can collide with 3D Objects

### ISSUE THREAD

**Issue by AJSmithJohnson** [nickworks/TreeOfLife#43]
We need to set it up so the player can collide with other 3D objects in our scene. So we need to change the player controller so the player can collide with other objects with Cube Colliders.

**Comment by nickworks** [comment]
Player prefab has been updated with a box collider, a rigidbody, and a PawnAABB3D. We should be good to go. If a particular level is broken, then the player controller in that level should be swapped out for the Player prefab.
