### ISSUE TITLE
Hey guys I could use some help

### ISSUE THREAD

**Issue by AJSmithJohnson** [nickworks/TreeOfLife#48]
So I closed a previous pull request but I went through your individual scenes and replaced all of the 2D colliders with 3D colliders so  it would be easy to jump back in and start to implement new stuff. But when I try to rebase and submit a merge request I get a bunch of merge conflicts and when I try to rebase or submit a pull request I get a bunch of weird merge conflicts. I could use some help here. Otherwise we each will have to add in 3D colliders back in.

**Comment by nickworks** [comment]
I merged a PR that was upstream from your branch, which is causing some issues. I'll work on fixing it.

**Comment by AJSmithJohnson** [comment]
Thanks! I think I'm going to work on fixing climbing to work in the new
movement system tomorrow and sunday.

I really like this way of doing projects. Also I'm not sure if jacob sent
you the discord link but I'll work on getting that to you tomorrow.

Thanks again!
Andrew,

**Comment by nickworks** [comment]
Fixed. I had to make an older branch, manually copy over specific changes, rebase, etc.
