### ISSUE TITLE
Player Rigid Body and Pawnaabb3d Bug

### ISSUE THREAD

**Issue by stormwarriors2** [nickworks/TreeOfLife#49]
From what I can see, For the majority of collision detection, we use the rigid body reference to detect the player, If the player has a rigid body and pawnAABB3D attached at the same time it causes an unintended issue of it sliding off the object and then spinning in circles in the z axis.

 While Hilarious it is still a bug. This might be because of the correction objects we use in Pawnaab3d for slanted or angled objects is conflicting with the Rigidbody component, meaning we might not be able to use rigidbody in Pawnaabb3d's current form or not at all.

Previous Pawnaabb interestingly allowed the player object to have both the rigidbody 2d and a PawnAABB to work. Now it no longer it does.

Here are some images. Tested on the Main Scene, attach a rigidbody to the player, and watch the fireworks.
![screenshot 144](https://user-images.githubusercontent.com/31518530/32408378-265a837a-c16d-11e7-851b-d359c4d11652.png)
![screenshot 143](https://user-images.githubusercontent.com/31518530/32408379-266952f6-c16d-11e7-873e-1a8b246a0005.png)

**Comment by nickworks** [comment]
Does checking "Is Kinematic" on the Rigidbody fix the issue?

**Comment by stormwarriors2** [comment]
Yes that seems to fix it!

**Comment by nickworks** [comment]
This issue should now automagically solve itself. The PlayerController requires a Rigidbody and automatically sets it to kinematic when it spawns. Yay!
