### ISSUE TITLE
Allow Camera to be switchable so that the designers can choose which direction it will change to

### ISSUE THREAD

**Issue by stormwarriors2** [nickworks/TreeOfLife#51]
Essentially allow for the camera to change sides if the designer wants the camera to pan out or to be on another side to establish a cinematic shot. This would immensely help for level design.

**Comment by nickworks** [comment]
Check out the new CameraDataNode in the master branch. Do you think this will work?

**Comment by nickworks** [comment]
Closing this request for now, as we likely won't implement a flipped camera for UX reasons. If we need a cinematic camera for something, that may require a different script anyway.
