### ISSUE TITLE
Player sometimes falls through the floor after jumping

### ISSUE THREAD

**Issue by AnIdeaGuy** [nickworks/TreeOfLife#57]
It seems to happen randomly. I was just playing around with it, but multiple times, I clipped through some solid objects.

**Comment by nickworks** [comment]
Are you in master or working from an older branch?

Is there a way to reliably replicate this bug? Does it seem to happen in a particular scene?

**Comment by AnIdeaGuy** [comment]
It happens in your 3D scene. And I can't seem to find a way to consistently replicate it. Like I said, it appears randomly.

EDIT: Actually, you can somewhat reliably replicate it if you go to the blocked off dead end on the far right side of the path, build up enough speed, jump, let go of jump, then press jump again right before you hit the corner, you sometimes phase through it.

**Comment by nickworks** [comment]
I think this might be a corner edge case. I will look into it.

**Comment by AnIdeaGuy** [comment]
It is. Turns out holding jump a second time doesn't make a difference.

**Comment by nickworks** [comment]
A diagonal raycast appears to fix this. 😄
