### ISSUE TITLE
Camera Rig Flips Behind Scenes

### ISSUE THREAD

**Issue by AJSmithJohnson** [nickworks/TreeOfLife#58]
All levels need to redesigned to use the node system or else the camera will flip behind the player so you will be viewing your scene backwards. So any of us with levels in the game or who want levels in the game need to redesign them with the nodes that have camera data on them and use the new camera rig.

**Comment by nickworks** [comment]
Fixed camera system so that it doesn't get jacked up. Closed issue; however, levels should still be updated to use the path node system.
