### ISSUE TITLE
Camera Node Functionality: Scene View indicators

### ISSUE THREAD

**Issue by Halbridious** [nickworks/TreeOfLife#61]
Right now there doesn't seem to be any information in the scene for where the camera is supposed to be pointed, so you have to adjust it by trial and error.  I'm looking into drawing some kind of helper that will indicate where the camera node data will orient the camera for each node.

**Comment by Halbridious** [comment]
Gizmos working, intractable handles pending, camera-view-in-scene pending.

**Comment by nickworks** [comment]
Gizmos PR accepted and merged.

**Comment by Halbridious** [comment]
Features are there, opening new issues for bugs related to them.  Closing the enhancement suggestion.
