### ISSUE TITLE
Path nodes are not instantiated as prefabs

### ISSUE THREAD

**Issue by Halbridious** [nickworks/TreeOfLife#68]
When adding new nodes to the path, the nodes are NOT prefabs, and any changes made to the master prefab are not applied to any created nodes.  If any functionality is added down the line paths could need to be rebuilt manually w/ any updated nodes.

**Comment by nickworks** [comment]
Did it! Read about the impact here: https://github.com/nickworks/TreeOfLife/commit/934f301635c3633341dbd2b98c97a070911eda7d
