### ISSUE TITLE
Game Controller Compatibility 

### ISSUE THREAD

**Issue by stormwarriors2** [nickworks/TreeOfLife#73]
Player Controller must work with Gamepad and controllers. If you press B on an xbox controller it creates an issue? Not really sure why that is happening.

**Comment by nickworks** [comment]
What do you mean by "creates an issue"?

**Comment by nickworks** [comment]
This is not an issue with the game controller. It is an issue with the respawn feature that was originally added alongside sticky webs. The same exception is thrown when the player presses 'R' on the keyboard.

I tagged Andrew, since I think he made the respawn feature.

**Comment by AJSmithJohnson** [comment]
Yeah! I'll work on it!

**Comment by MarkVDZ** [comment]
Fixed in issue #84
