### ISSUE TITLE
Strange Physics bug in main Level 

### ISSUE THREAD

**Issue by stormwarriors2** [nickworks/TreeOfLife#74]
Currently on this level the player can clip through angled objects on this main level if you drop from a certain distance.

![interesting](https://user-images.githubusercontent.com/31518530/32628948-935eb71a-c565-11e7-8e7f-93f1dbbfa92e.PNG)

**Comment by nickworks** [comment]
Related to issue #57 and #29 and #30.

**Comment by nickworks** [comment]
This is fixed with some recent changes to the PawnAABB3D class.
