### ISSUE TITLE
GUICamera rendering in game view

### ISSUE THREAD

**Issue by Halbridious** [nickworks/TreeOfLife#89]
may need to change how I'm getting GUI camera since it appears to render in-game if it's not been closed before hand.

**Comment by nickworks** [comment]
I fixed this by removing that feature. Let's just use the editor window instead.

**Comment by Halbridious** [comment]
I'd have to check, but I believe if the Editor Window is open it will render the editor window camera instead of the main camera, so there may still be some bugs.  Will be looking into it shortly.
